apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:CptGk0AkE7Okqy2ECJkspLy7RgN7skTqfZdyvabM3pyi0+OM3SSfoYzDFn45V2E6VerlqCtOxgNay4TkuFItyghUtcQ6vRm/Cy6kYB6OuRiCmk0y4tNMeFi32RtuVArgR+iOOeO4uEXvmdfTa5x7fA==,iv:W4dTHPC9sVnd6bqQju8iOPxUJdGmRc82l0KniHYPUN0=,tag:TfI+fIQ0BO4dBUBF1VCv6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T10:42:30Z"
    mac: ENC[AES256_GCM,data:n2m5VT4T8a5O6Q6Jk/aZ3pBMNRiafcVu7pbw4BajgAy1H9IPzaz92zzCX75sgDTQ2s/sGNimvsGVyRXDPCuKkWGCYQDYAzYjAiaAReiB0efxWikRR0+KZiUALa6DZtpJGfuTJUAUDBYVLO91qf9HUO8q93/txmL7rE4Dnsz/e/w=,iv:RHbANPG0aHTsindAtTk70Dp6Z/1YWzJxJefrstIuvBU=,tag:uRsGcntUsTzQxaJ5dl66KA==,type:str]
    pgp:
        - created_at: "2021-07-06T10:42:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4egbOXuCPsgAQ/9GOEFX0+gEe03mmemGByZVn7y+pfTrIz22Vfk7QVQj76L
            01ap0D0G2hIIICAuyBMjzbO5d3dgm0a7RX6OHPLoAt5xFpJ3waK3mrdEgjaNS+Os
            1yxXRrzle/Gl8aHERXDAjiX8Pb0oKLh8gx5ovRhl1QCVt/gJBofFXkubDvvfuym9
            F3uHIZKBJbqKrNOiM7ZsszPJ6vxuJSBuzpSfwDAeyYCSEY6i48aUZ9eyUse+t/Fb
            6KFikOFThpGKXpowYDVnrtWXWbUVN+weeoMgbkOQbrqOVFPRxc9BfBhlkD9u/Qre
            7iQOSYbXQVYfyqURtQacoR2yKcQPlq3hfB4bez/OAoqvOtfnRnOgWgroYW3bwjuI
            JefSxYDK4ROIoXf0YF3tMYIYdoU7sVqYoyKxS5pvKJ0GVmIXqZDKt3WHgzLzzrQ1
            sFJ3t9/iJZ6W7vv4+DMKq2oJc6TK85ZwBFaJmE3jwn7ze/5JAFNc0MHUmHfr2W0u
            pXITZhBg1KwOPji5fVFLckiiAcHB4NOpmzSzVOEZOO1tVS65T3pYwlsy5zngXDJ1
            CAT/lSvScj3RI5ZlWtPFpNhAyycobsG07rFW7sJmpalUdpne04l2A/UrkeSVZt03
            Zsn0zdzfbJG87mGb8ry5uo1F663X7rWdcx8fSqMAJRiTDSWHNUmv4mgmDysI2U/S
            XgFrGQ/Ftu3Rhcz2WV7JclKkQcCC3tDhRF7/Gbv0W0ojx9MMsMR/PkGJJD9yzFQ5
            XZkMP2fexjkcSAWc16IWuQN+GaC2RjsoMRz/Q+OZEIzRoppirACJOw0zR5Tfx1g=
            =EXhk
            -----END PGP MESSAGE-----
          fp: E9CA587C9BDF783638985F00C2B1E90484512DDB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
